GET http://localhost:3001/auth

###

POST http://localhost:3001/auth/register
content-type: application/json

{
    "username":"sofiliz898",
    "email":"sofi.system32@gmail.com",
    "password":"123456"
}

###

POST http://localhost:3001/auth/login
content-type: application/json

{
    "username":"sofi1234",
    "password":"12345"
}

###
GET http://localhost:3001/auth/test
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic29maTEyMzQiLCJpYXQiOjE2OTc4MTUzMDV9.jaTk6WFikMyLqxK4zomoO3_fBwJFCNhq9YDOsjbZqq0